### ISSUE TITLE
Requests appear aborted before handler over HTTP/1.1

### ISSUE THREAD

**Issue by devinivy** [connectrpc/connect-es#1025]
**Describe the bug**

The signal `request.signal` on a `UniversalServerRequest` is aborted as soon as the request body has been read, at least over HTTP/1.1.  As a result, for most rpc handlers the request appears aborted before the handler begins (since the request has already been read).  Ideally the signal would not be aborted until the underlying connection closes.

**To Reproduce**

Create an rpc handler using node HTTP/1.1, hit the endpoint with a POST request, and read `request.signal.aborted` at the top of the handler.  It will appear aborted (i.e. take the value `true`) even though the client and server maintain a connection, and the client will be able to receive the response.

**Environment (please complete the following information):**
- @connectrpc/connect-node version: on latest `1.3.0`, likely going back further as well.
- Node.js version: v16+

**Additional context**

The issue most likely goes back to this change in node v16 https://github.com/nodejs/node/issues/40775, where the `'close'` event on an `IncomingMessage` indicates that you've read the whole message, whereas in the past it represented the resource underlying the request (i.e. would not close until the request/response flow ended, either due to actions taken by the server or client).  I believe the more straightforward fix may be to use the node [response object's `'close'` event](https://nodejs.org/api/http.html#event-close_2) rather than the request object's here: https://github.com/connectrpc/connect-es/blob/fa7726b598391b8dfd0e9f14e27dcc87aca74146/packages/connect-node/src/node-universal-handler.ts#L120-L121

**Comment by srikrsna-buf** [comment]
Thank you for reporting and for finding the node issue! I can reproduce. Not sure if relying on the response is the solution here.

**Comment by lourd** [comment]
I also just ran into this issue when switching a service from http2 to http. My logger includes whether or not a response was aborted. It was very confusing and concerning to see that all of our requests were now being aborted. It also broke logic in our code that uses the abort signal.

This is quite a significant bug. It effectively eliminates http1 as an option for any moderately complex Connect server.

**Comment by timostamm** [comment]
> Thank you for reporting and for finding the node issue! I can reproduce. Not sure if relying on the response is the solution here.

@srikrsna-buf, can you still reproduce this after https://github.com/connectrpc/connect-es/pull/1206?

**Comment by srikrsna-buf** [comment]
I still [can](https://github.com/connectrpc/connect-es/commit/90b2bb92efed7da58243b83e56210e2459904386), the fix in #1181 seems to work, but I am trying to see if we can do this in a backward compatible way.

**Comment by timostamm** [comment]
> I still [can](https://github.com/connectrpc/connect-es/commit/90b2bb92efed7da58243b83e56210e2459904386), the fix in #1181 seems to work, 

Thanks 😞 

> but I am trying to see if we can do this in a backward compatible way.

The function has a comment basically marking it as private, but I agree it would be good to not break.
