### ISSUE TITLE
Root interceptors are overwritten when service interceptors are also defined

### ISSUE THREAD

**Issue by sushidesu** [connectrpc/connect-es#1077]
**Is your feature request related to a problem? Please describe.**

When using `router` with `interceptors`, the `interceptors` passed to the router's root are ignored if `interceptors` are also passed to the service. In this case, only the service interceptors are applied. This affects various plugins, such as `@connectrpc/connect-express` and `@connectrpc/connect-fastify`.

Here's a code example that reproduces the issue:

```typescript
import type { ConnectRouter } from "@connectrpc/connect"
import { ElizaService } from "../gen/eliza_connect"
import { fastify } from "fastify"
import { fastifyConnectPlugin } from "@connectrpc/connect-fastify"

const elizaService = (router: ConnectRouter) =>
  router.service(
    ElizaService,
    {
      async say(req) {
        return {
          sentence: `You said: ${req.sentence}`,
        }
      },
    },
    {
      interceptors: [
        (next) => async (req) => {
          console.log("2. service interceptor")
          return await next(req)
        },
      ],
    }
  )

async function main() {
  const server = fastify()
  await server.register(fastifyConnectPlugin, {
    routes: (router) => {
      elizaService(router)
    },
    interceptors: [
      (next) => async (req) => {
        // ignored
        console.log("1. root interceptor")
        return await next(req)
      },
    ],
  })
  await server.listen({ host: "localhost", port: 8080 })
  console.log("server is listening at", server.addresses())
}

void main()
```

When running this code and sending a request, only `2. service interceptor` is logged, indicating that the root interceptor is being overwritten.

Here is a repository to reproduce this issue: https://github.com/sushidesu/test-connect-es-interceptors

The issue seems to be caused by the options being overwritten in this part of the code: https://github.com/connectrpc/connect-es/blob/f5f1641e9b0feeec53fa751221d5ecf0fc05a903/packages/connect/src/router.ts#L195-L203

**Describe the solution you'd like**

This behavior is difficult to predict. I would like connect-es to apply both root and service interceptors when they are defined, rather than overwriting the root interceptors. This request is for Connect for Node.js.

**Describe alternatives you've considered**

If this is the intended behavior, I would like to add documentation to clarify this.

**Additional context**

If a fix is needed, I'd be happy to create a pull request to address this issue.

**Comment by srikrsna-buf** [comment]
It is as intended, we can add documentation to clarify this. 

It is trivial to pass the root interceptors to service interceptors when they replace, but if the service interceptors are additive, then there would be no way to replace or run before the root interceptors.
