### ISSUE TITLE
Test files included in shipped package of connect-node

### ISSUE THREAD

**Issue by lourd** [connectrpc/connect-es#1182]
**Describe the bug**

The test suites for connect-node are being shipped. It would be nice if they weren't. They're quite small, but it's still a waste of bandwidth and storage.

**To Reproduce**

You can see the test files here on unpkg. They're even duplicated -- they're shipped in both the esm and cjs directories

- https://unpkg.com/browse/@connectrpc/connect-node@1.4.0/dist/esm/
- https://unpkg.com/browse/@connectrpc/connect-node@1.4.0/dist/cjs/

The [testdata directory](https://unpkg.com/browse/@connectrpc/connect-node@1.4.0/dist/esm/testdata/) probably isn't needed either.

**Comment by smaye81** [comment]
Thanks for creating. This has actually been fixed in https://github.com/connectrpc/connect-es/pull/1112, but it hasn't been released yet. So versions after v1.4.0 should have the correct distribution. Sorry for any inconvenience.

**Comment by lourd** [comment]
Oh nice, that's great! Thanks for already doing the work :)
