### ISSUE TITLE
Peer dependency conflict between @connectrpc/connect-web and @bufbuild/protobuf

### ISSUE THREAD

**Issue by dghubble** [connectrpc/connect-es#1248]
**Describe the bug**

As clearly as you can, please tell us what the bug is.

**To Reproduce**

Trying to update to the the current versions of `@bufbuild/protobuf` and `@connectrpc/connect-web`:

```
  "dependencies": {
    "@bufbuild/protobuf": "^2.1.0",
    "@connectrpc/connect-web": "^1.1.2"
  }
```

```
npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: notepad@0.0.1
npm error Found: @bufbuild/protobuf@2.1.0
npm error node_modules/@bufbuild/protobuf
npm error   @bufbuild/protobuf@"^2.1.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @bufbuild/protobuf@"^1.10.0" from @connectrpc/connect-web@1.5.0
npm error node_modules/@connectrpc/connect-web
npm error   @connectrpc/connect-web@"^1.1.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

As of `@connectrpc/connect-web` 1.5.0, its pinned to `@bufbuild/protobuf` ^1.10.0 - [see here](https://github.com/connectrpc/connect-es/blob/v1.5.0/packages/connect-web/package.json#L56).

Is this expected? If they're incompatible, is there a timeline of when they'll be compatible? Or is there a recommendation if I should prefer to update protobuf or connect?

**Environment (please complete the following information):**

- @connectrpc/connect-web version: (for example, `0.1.0`) 1.5.0
- @connectrpc/connect-node version: (for example, `0.1.0`)
- Frontend framework and version: (for example, `react@18.2.0`)
- Node.js version: (for example, `18.0.0`)
- Browser and version: (for example, `Google Chrome 103.0.5060.134`)

If your problem is specific to bundling, please also provide the following information:

- Bundler and version: (for example, `webpack@5.74.0`)
- Bundler plugins and version: (for example `compression-webpack-plugin@10.0.0`)
- Bundler configuration file:

```js

```

**Additional context**

I'm mostly just trying to resolve dependabot PRs on an older project, I have no need for the features of either, its just keeping up with maintenance. These two have been incompatible and outstanding for several months now.

**Comment by dghubble** [comment]
To update as many dependencies as possible and migrate from bufbuild/connect-web to connectrpc/connect-web, I went with upgrading connect-web and leaving bufbuild/protobuf on an old version to satisfy.

```
	"dependencies": {
		"@bufbuild/protobuf": "^1.10.0",
		"@connectrpc/connect-web": "^1.1.2"
	}
```

I'd love to know if buf folks have a policy or plans here?

**Comment by srikrsna-buf** [comment]
Hey @dghubble. V1 of connect only works with V1 of protobuf. We are actively working on v2. We released a beta yesterday, you can check it out [here](https://github.com/connectrpc/connect-es/discussions/1247).
