### ISSUE TITLE
Running npx @connectrpc/connect-migrate@beta createPromiseClient -> createClient is broken

### ISSUE THREAD

**Issue by raphaeltm** [connectrpc/connect-es#1257]
**Describe the bug**

I ran `npx @connectrpc/connect-migrate@beta`. This resulted in a few changes, including switching `createPromiseClient` to `createClient`. But `createClient` doesn't seem to exist?

![Code 2024-10-03 19 08 47](https://github.com/user-attachments/assets/3a6ee2d8-8470-4219-9d76-02ea3bae3d76)

**Environment (please complete the following information):**

Relevant deps:

```
    "@bufbuild/buf": "^1.44.0",
    "@bufbuild/protobuf": "^2.1.0",
    "@bufbuild/protoc-gen-es": "^2.1.0",
    "@connectrpc/connect": "^2.0.0-beta.1",
    "@connectrpc/connect-node": "^2.0.0-beta.1",
```

Node version: `v19.9.0`

**Comment by srikrsna-buf** [comment]
It might be because of vscode, can you reload the vscode window? Because I see that the deps updated to `2.0.0-beta.1` and it does [export](https://www.npmjs.com/package/@connectrpc/connect/v/2.0.0-beta.1?activeTab=code) `createClient`.

**Comment by raphaeltm** [comment]
🤦 
@srikrsna-buf that was it. I had a different error in my logs (turns out you now require a protocol for the base url in this version) and assumed they were related. I need sleep 😅
