### ISSUE TITLE
httpVersion check for `createRouterTransport`

### ISSUE THREAD

**Issue by nicole0707** [connectrpc/connect-es#1258]
**Is your feature request related to a problem? Please describe.**
When Connect upgrade to v1.5, it starts to check the gRPC code and gRPC message from trailer or header by default. We encountered an issue when using`createRouterTransport` with `httpVersion: 1.1`, the test didn't pick up the breaking change for us.

**Describe the solution you'd like**
I am wondering if possible to check the transport option when using `createRouterTransport`, ensure it's similar to testing against with real service.

Please specify whether the request is for Connect for Web or Connect for Node.js.
Connect for Node.js

**Describe alternatives you've considered**
I am not sure of the best way to handle this, but perhaps we could verify the transport option like enforce checking the `httpVersion` starting from v1.5.

**Additional context**
https://github.com/connectrpc/connect-es/pull/1205/files#diff-92e5a379d00b073cbd57f841a9669260a8e9603c2015e09aeeb49daf6fe788b8R40

**Comment by nicole0707** [comment]
BTW, I am happy to contribute to implementing the change if we come up with a solution. Cheers!

**Comment by timostamm** [comment]
Can you provide some details on where you started to see the error with v1.5? Do you mean that the tests ran fine with `createRouterTransport`, but running against a real server, you started seeing the error?

**Comment by timostamm** [comment]
Thanks! Can you give an example of where you are setting `"httpVersion":1.1`?  Can you share what server software the client was running against?

**Comment by nicole0707** [comment]
Sure, I  forked the `examples-e` and updated `createGrpcTransport` with `createConnectTransport`,  the `httpVersion` is also set to `1.1`. All tests pass, and there are no issues on `npm build` https://github.com/connectrpc/examples-es/compare/main...nicole0707:examples-es:main. However, when I run `npm start`, I encounter this issue.

<img width="629" alt="image" src="https://github.com/user-attachments/assets/04e1ab59-8753-4688-8776-732612f84e9a">

The root cause is that we are not properly [validate the trailer ](https://github.com/connectrpc/connect-es/blob/main/packages/connect/src/protocol-grpc/validate-trailer.ts#L32) when calling [createRouterTransport](https://github.com/connectrpc/connect-es/blob/main/packages/connect/src/router-transport.ts#L28). I found [one relevant unit test](https://github.com/connectrpc/connect-es/blob/main/packages/connect-node/src/node-readme.spec.ts#L127-L144) covering `HTTP/1.1`. However, it doesn't account for the case where we are using the gRPC protocol. 

What would be the best way to address this issue? Should we remove the `HTTP/1.1` option from the`NodeTransportOptions`? Cheers!

**Comment by srikrsna-buf** [comment]
The gRPC protocol doesn't work on HTTP/1.1, it only works where HTTP/2 trailers are supported.

**Comment by nicole0707** [comment]
Yes. Considering that we will check trailers by default with the gRPC protocol, should we throw an error or simply not allow HTTP/1.1, instead of swallowing the issue during the build?

**Comment by srikrsna-buf** [comment]
If you wan to use gRPC protocol you should only use HTTP/2

**Comment by nicole0707** [comment]
The fact is we didn’t use HTTP/2 before Connect 1.5, and it ended up breaking our application in production without any issues during the build or unit tests when we upgraded. I believe we need to review our strategy regarding the HTTP version.

**Comment by nicole0707** [comment]
If the trailer check is only relevant for HTTP/2, we should limit it to HTTP/2 checks. Otherwise, we shouldn’t allow HTTP/1.1 for the gRPC protocol. I’m just wondering, what was the intention behind adding the trailer check in Connect 1.5?

**Comment by srikrsna-buf** [comment]
> I’m just wondering, what was the intention behind adding the trailer check in Connect 1.5

If there is no trailer check, errors will not be reported. The protocol uses trailers to send error codes and error details.

**Comment by srikrsna-buf** [comment]
Hey! In the example, the server actually isn't sending the trailers. We think it might be best to not support for `1.1` for gRPC as most implementations don't support it. This will be breaking change so will do this in v2

**Comment by timostamm** [comment]
Krishna is right, gRPC implementations typically require HTTP/2, but the protocol itself does not. connect-es and connect-go can serve and call gRPC over HTTP 1.1. 

For example, we can modify the [connect-go example](https://github.com/connectrpc/examples-go) to serve only HTTP 1.1: 

```go
// ...

func main() {
	mux := http.NewServeMux()
	mux.Handle(elizav1connect.NewElizaServiceHandler(
		NewElizaServer(time.Millisecond * 100),
	))
	err := http.ListenAndServe(
		"127.0.0.1:8080",
		mux,
	)
	if err != nil {
		panic(err.Error())
	}
}
```

This service can be called from a connect-go client with gRPC, or from a connect-es client with `createGrpcTransport({ httpVersion: "1.1", baseUrl: "http://127.0.0.1:8080" })`. 

This works for streaming too - with the exception of full-duplex streaming, which isn't possible in HTTP 1.1. The status, which is typically sent as a HTTP/2 trailer, is sent as a [HTTP 1.1 trailer](https://httpwg.org/specs/rfc9112.html#chunked.trailer.section).

So why does the connect-es client raise an error when it calls the same connect-go example service, hosted on `demo.connectrpc.com`? (Thanks for the repro, @nicole0707!)

It turns out the demo is not deployed correctly, and HTTP 1.1 trailers are lost. If the service were to raise an error, the client would never know. The additional checks in connect-es v1.5 verify that trailers are present as a safe-guard against exactly this situation.

**Comment by nicole0707** [comment]
Thanks @timostamm @srikrsna-buf. The plan is reasonable for me. I appreciate your time and help! 👏

**Comment by timostamm** [comment]
In the upcoming v2, we're disabling support for gRPC over HTTP 1.1.
