### ISSUE TITLE
Allow user-provided User-Agent request header

### ISSUE THREAD

**Issue by polRk** [connectrpc/connect-es#1271]
https://github.com/connectrpc/connect-es/blob/3d1019187838069b849b1ec216d7fd795d0f878d/packages/connect/src/protocol-grpc/request-header.ts#L43

User header must have priority and override useragent header defined buy library

**Comment by timostamm** [comment]
The user-agent set by connect-es is important to use because it helps users and us to diagnose issues. 

Can you provide some details on why it is important to you to override the header?

**Comment by polRk** [comment]
> The user-agent set by connect-es is important to use because it helps users and us to diagnose issues.
> 
> Can you provide some details on why it is important to you to override the header?


It is very important to add information not only about connect-es, but also about runtime and even about the product

**Comment by timostamm** [comment]
Okay, it's reasonable to _not_ set the User-Agent request header if the user already provided one via `CallOptions.headers`. 

This applies to the Connect, gRPC, and gRPC-Web transports, but not to the ones from `@connectrpc/connect-web`, since we do not set the header there (https://github.com/connectrpc/connect-es/pull/912). 

Until this change is made, you can use an interceptor to set a custom user agent:

```ts
const transport = createConnectTransport({
  baseUrl: "https://demo.connectrpc.com",
  interceptors: [
    (next) => async (req) => {
      req.header.set("User-Agent", "FOO");
      return await next(req);
    }
  ]
});
```

**Comment by polRk** [comment]
The problem is: Using interceptors introduces unnecessary overhead, especially when using AsyncLocalStorage.

**Comment by timostamm** [comment]
Closed by https://github.com/connectrpc/connect-es/pull/1272.

It would be convenient to have a transport-level option, but we try to keep the API lean. Interceptors (as suggested in https://github.com/connectrpc/connect-es/issues/1271#issuecomment-2411048990), shouldn't have a perceivable impact on performance.
