### ISSUE TITLE
Cannot connect with Bun

### ISSUE THREAD

**Issue by polRk** [connectrpc/connect-es#1275]
**Describe the bug**

```
error: Premature close
 code: "ERR_STREAM_PREMATURE_CLOSE"

      at new NodeError (node:stream:443:20)
      at node:stream:920:23
```

**To Reproduce**

https://github.com/polRk/ydb-nodejs-genproto/tree/polrk/buf%2Bconnectrpc

**Environment (please complete the following information):**

- bun: 1.1.30
- @bufbuild/protobuf: "^2.2.0"
- @connectrpc/connect: "^2.0.0-beta.2"
- @connectrpc/connect-node: "^2.0.0-beta.2"

**Additional context**
Works on Nodejs and Deno.

**Comment by timostamm** [comment]
Bun aims for compatibility with the Node.js APIs, and asks to open an issue if you run into any bugs. Please open an issue against Bun.
