### ISSUE TITLE
Support @bufbuild/protobuf@^2

### ISSUE THREAD

**Issue by wenerme** [connectrpc/connect-es#1286]
**Is your feature request related to a problem? Please describe.**

new to connect-es, after some try and fail, find out connect-es require `@bufbuild/protobuf@^1` , `@bufbuild/protoc-gen-es@^1`, hope connect-es support v2. I don't find existing issues for this, so I create this one.

**Comment by smaye81** [comment]
Hi there. Just to clarify -- all 1.x versions of Connect-ES require 1.x versions of `@bufbuild/protobuf`. However, we've published a v2 release candidate of Connect-ES which can be used with v2 versions of `@bufbuild/protobuf`. You can find that version here: https://www.npmjs.com/package/@connectrpc/connect/v/2.0.0-rc.1
