### ISSUE TITLE
Add support for Next.js v15

### ISSUE THREAD

**Issue by smaye81** [connectrpc/connect-es#1289]
Next.js v15 was recently [released](https://nextjs.org/blog/next-15). We should add support for it by first testing w/ v15 and then updating our dependency constraints for `connect-next`.

Prior art for upgrading to v14 [here](https://github.com/connectrpc/connect-es/pull/1159).

**Comment by timostamm** [comment]
Adding support in v2 in https://github.com/connectrpc/connect-es/pull/1290
