### ISSUE TITLE
connect-node client does not support mocking with MSW

### ISSUE THREAD

**Issue by mykhailo-hrynko** [connectrpc/connect-es#1325]
# HTTP requests made with `connect-node` transport are not intercepted with MSW.

I have a ConnectRPC server running the default `ElisaService`.

Another Node.js app is using it via `connect-node` transport. In order to write func tests I need to mock all external HTTP requests.

I use [MSW](https://github.com/mswjs/msw) lib for mocking (See the code below).

The main issue is that connect-node requests are not intercepted, because of the way `node:http` module is imported in the `connect-es/packages/connect-node`. 

- The issue describing the problem https://github.com/mswjs/msw/issues/2049
- The PR fixing it https://github.com/connectrpc/connect-es/pull/1324

The simplest code to reproduce the problem:

```js
import { createClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-node";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";

const BASE_URL = "Connect server URL";
const API_URL = BASE_URL + "path to your ElisaService/Say";

const handler = http.post(API_URL, () => HttpResponse.json({ sentence: "42" }));
const server = setupServer(handler);
server.listen({ onUnhandledRequest: "error" });

const transport = createConnectTransport({
  baseUrl: BASE_URL,
  httpVersion: "1.1",
  useBinaryFormat: false,
});

const client = createClient(ElisaService, transport);
const res = await client.say({ sentence: "Hello" });

console.log(res.sentence); // should be 42
```

**Environment:**

- @connectrpc/connect-node version: 1.6.1
- Node.js version: (for example, `20.17.0`)

**Comment by timostamm** [comment]
The example you give for mocking the RPC Say would probably work, but it has several downsides:
- It only works for JSON, not for binary requests
- It is very impractical to mock the message enveloping that gRPC, gRPC-web, and Connect (with streaming RPCs) use
- It does not support HTTP/2
- The JSON response is not type-safe
- It does not support cancellation and timeouts
- It's not trivial to mock errors

Have you seen our [documentation for testing](https://connectrpc.com/docs/node/testing)? `createRouterTransport` solves all of the problems above, you only need to inject the transport into the code under test.

If the problems do not affect you, there's another simple solution: You can use a transport from `@connectrpc/connect-web`, which simply uses `fetch` under the hood. If I'm not mistaken, `msw` can intercept `fetch` calls reliably, so this should allow you to mock with `msw`.

**Comment by mykhailo-hrynko** [comment]
@timostamm Thank you for quick response&

My situation is that I have 2 microservices communicating via connect. And I need to test the client. So in these test I don't control how the server is configured. I just want to mock external calls

I'll try with `connect-web`. Thanks!
