### ISSUE TITLE
Support extensions for debugging grpc in browsers

### ISSUE THREAD

**Issue by mindyourlifeguide** [connectrpc/connect-es#1365]
I would like to be able to debug in the browser, but the documentation doesn't mention how to do it.

I wish the connect-es documentation included instructions or examples of how to do this.

I suggest adding the methods I use or you can describe yours and I'll gladly switch to them.

There are extensions for debugging grpc in browsers https://github.com/SafetyCulture/grpc-web-devtools.

Integration with buf v1 was done via the described instruction in the extension repository.

A different integration is needed for buf v2. @bhollis did a cool job and already implemented it in https://www.npmjs.com/package/connect-devtools

Could you please add a mention of this in the documentation?

**Comment by srikrsna-buf** [comment]
Hey! Do you mean recommend these projects in the official docs?

**Comment by mindyourlifeguide** [comment]
@srikrsna-buf Yes, or your options for debugging in the browser

**Comment by mindyourlifeguide** [comment]
@srikrsna-buf If needed, I can make a pull request with an updated repository description with updated information

**Comment by timostamm** [comment]
Thanks for the offer! I'm afraid we don't have a good place for this information yet, but I've added it to the [documentation backlog](https://github.com/connectrpc/connectrpc.com/issues/41).
