### ISSUE TITLE
Enabling 'include_imports' in protoc build command broken (or documentation gap)

### ISSUE THREAD

**Issue by martijnjanssen** [connectrpc/connect-es#1366]
Updating all dependencies (@bufbuild/protobuf, @bufbuild/protoc-gen-es, @connectrpc/connect, @connectrpc/connect-web) to V2 results in the error `Could not resolve "./buf/validate/validate_pb"`. From the migration guide it is very clear that this issue is to be resolved by setting `include_imports: true` in the `buf.build` file. Great!

What is missing is how to include it in a `protoc` build command. I cannot figure out how to correctly enable that setting from the cli.
```bash
protoc \
	-I. \
	-I./bufbuild/protoc-gen-validate \
	-I./proto \
--plugin ./node_modules/.bin/protoc-gen-es \
--es_out ./proto \
--es_opt target=ts \
--es_include_imports \
*.proto
```

Results in the error:
`Unknown flag: --es_include_imports`

I cannot seem to figure out how to set it, or it is broken, given how new the setting is.

**Comment by srikrsna-buf** [comment]
`include_imports` is a feature of `buf` and is not part of the plugin. For `protoc` you will have to generate code for validate files as well:

```bash
cd ./bufbuild/protoc-gen-validate
protoc \
	-I. \
--plugin ../../node_modules/.bin/protoc-gen-es \
--es_out ../../proto \
--es_opt target=ts \
**/*.proto
```

**Comment by martijnjanssen** [comment]
Right, that helps a lot. Cheers!
