### ISSUE TITLE
Ping timeouts for streams cause `Missing status` errors.

### ISSUE THREAD

**Issue by jrandolf** [connectrpc/connect-es#1367]
**Describe the bug**

This can be seen as a feature request or a bug.

If a stream doesn't produce anything for a while and a client's ping timeout passes, the client will stop the stream and error here https://github.com/connectrpc/connect-es/blob/84a65b99d38807d363cca45472de8eefd0aee9a5/packages/connect/src/protocol-grpc/transport.ts#L258 looking for a status header (which would not exist because the client stopped the stream due to timeout).

**Expected**

A client-side error caused by ping timeout.

**To Reproduce**

Internal code, but the above description should be sufficient.

**Environment (please complete the following information):**

- @connectrpc/connect-node version: v2.0.0
- Frontend framework and version: 19
- Node.js version: 22

**Additional context**
This can probably be resolved by throwing a connect error wherever the ping times out.

**Comment by timostamm** [comment]
Thanks for the report, Randolf. 

> This can probably be resolved by throwing a connect error wherever the ping times out.

We do, in https://github.com/connectrpc/connect-es/blob/v2.0.0/packages/connect-node/src/http2-session-manager.ts#L667

Can you provide the exact Node version? A reproducible example would be very helpful.

**Comment by jrandolf** [comment]
After some more debugging, it appears the timeout is not the problem. The http2 client response stream for some reason resolves with an empty value. I'll debug this further and get back to you.

**Comment by jrandolf** [comment]
Figured it out. It was caused by [Envoy Gateway](https://gateway.envoyproxy.io/docs/tasks/traffic/http-timeouts/) timing out my requests. Nothing wrong here!
