### ISSUE TITLE
$typeName returned in response payload when calling service method

### ISSUE THREAD

**Issue by StarpTech** [connectrpc/connect-es#1373]
**Describe the bug**

Hello, we're currently investigating the migration from v1 to v2. Thanks to your [migration guide](https://github.com/connectrpc/connect-es/blob/main/MIGRATING.md), the migration is straightforward, although it requires a lot of effort.

Unfortunately, we ran into the following issue in our tests when we used the connect client to make requests against our server.

```
AssertionError: expected [ { …(3) } ] to deeply equal [ { key: 'team', value: 'A' } ]

- Expected
+ Received

  Array [
    Object {
+     "$typeName": "wg.cosmo.platform.v1.Label",
      "key": "team",
      "value": "A",
    },
  ]
```

Is this the intended behaviour? We don't see `$typeName` as part of the response e.g. in the Next.js frontend. We're curious why this only appears server side. Thanks!

**Comment by StarpTech** [comment]
I think it is related to [this](https://github.com/connectrpc/connect-es/blob/main/MIGRATING.md#plainmessage-removed). In order to fulfill the type we now return `create(Type, init)` in the service method.

**Comment by srikrsna-buf** [comment]
The `$typeName` is a special property to identify the type of a message. This is new in `@bufbuild/protobuf` v2. This won't be part of the response. For comparison in tests, it is best to use the `equals` function exported from `@bufbuild/protobuf`. 


> As a side note: We also experienced type issues when implementing a service. Is this known?
> 
> ```ts
>  router.service(PlatformService, {
>       getNamespaces: async (req, ctx) => {
>         return {} // Valid
>       },
>     }, handlerOptions);
> ```

This is possible in v1 as well. This is mainly because protobuf messages have default values. The return type matches the second parameter passed to `create`.

**Comment by StarpTech** [comment]
Hi @srikrsna-buf, I don't understand your conclusion. I know, it is there to identify a message but why is it part of my client response? I never had defined this in my proto definition.

> For comparison in tests, it is best to use the equals function exported from @bufbuild/protobuf.

This will change the way how we do assertions in our code base. Would you be open to support a mode where those fields are omitted?

**Comment by srikrsna-buf** [comment]
> why is it part of my client response

It is not part of the wire, it is only part of the objects returned from the clients. It is similar to retuning a class with a couple of additional methods and properties (that are not part of proto) which was the case in v1. 



> Would you be open to support a mode where those fields are omitted?

We won't be supporting such a mode as our suggestion is to keep the `$typeName`. But you can wrap `createClient` to remove the `$typeName` fields from the response.



> Shouldn't the expectation be here to validate the proto message definition?

It does match the definition, the required fields have to be set. Only if a message has no required fields will it allow `{}`, if it is not the case please open an isssue on [bufbuild/protobuf-es](https://github.com/bufbuild/protobuf-es)

**Comment by intech** [comment]
@StarpTech If you need to work with JSON, you can use envoy gRPC-JSON transcoding or interceptor:
```js
import { fromJson, toJson } from "@bufbuild/protobuf";

/**
 * @typedef {import("@bufbuild/protobuf").DescMessage} DescMessage
 */
/**
 * Change every stream message
 * @returns {AsyncGenerator<*, void, *>}
 * @param {DescMessage} schema
 * @param {AsyncIterable<MessageShape<Object>>} stream
 * @yield {MessageShape<Object>} message
 */
async function* fromJsonStream(schema, stream) {
    for await (const message of stream) {
        yield fromJson(schema, message, { ignoreUnknownFields: true });
    }
}

/**
 * Change every stream message
 * @param {DescMessage} schema
 * @param {AsyncIterable<MessageShape<Object>>} stream
 * @returns {AsyncGenerator<*, void, *>}
 */
async function* toJsonStream(schema, stream) {
    for await (const message of stream) {
        yield toJson(schema, message, { ignoreUnknownFields: true });
    }
}

/**
 * Connect RPC Interceptor for auto json serializer
 * @returns {function(*): Promise<*>}
 */
export default function serializerInterceptor(next) {
    return (req) => {
        if (req.service.name !== "ServerReflection") {
            if (req.stream) {
                req.message = toJsonStream(req.method.input, req.message);
            } else {
                req.message = toJson(req.method.input, req.message, { alwaysEmitImplicit: true });
            }
        }
        return next(req).then((res) => {
            if (res.service.name !== "ServerReflection") {
                if (res.stream) {
                    res.message = fromJsonStream(res.method.output, res.message);
                } else {
                    res.message = fromJson(res.method.output, res.message, { ignoreUnknownFields: true }); // FOR ENUM
                }
            }
            return res;
        });
    };
}
```

```js
import serializerInterceptor from "./interceptors/serializerInterceptor.js";
// ...
connectNodeAdapter({
            routes,
            interceptors: [serializerInterceptor],
            jsonOptions: {
                emitDefaultValues: true, // this deserialization default value
            }
        }),
```
