### ISSUE TITLE
Headers in fetch causing an issue using Node

### ISSUE THREAD

**Issue by mfridman** [connectrpc/connect-es#203]
I was testing remote generation, and came across an issue when using Node `v18.1.0`. From what I understand the latest version of Node supports ["browser-compatible APIs"](https://nodejs.org/ru/blog/announcements/v18-release-announce/), notably `fetch`.

So I was expecting this to work.

```js
import { ElizaService } from "@buf/local_connect-web_bufbuild_eliza/buf/connect/demo/eliza/v1/eliza_connectweb.js";
import { createPromiseClient, createConnectTransport } from "@bufbuild/connect-web";

const client = createPromiseClient(
  ElizaService,
  createConnectTransport({ baseUrl: "https://demo.connect.build" })
);
const { sentence } = await client.say({ sentence: "hello" });
console.log(sentence);
```

But, I was getting back the following error, notice the `HTTP 415 Unsupported Media Type`.

```
file:///Users/mfridman/debug-generation/connect-web/old-remote/node_modules/@bufbuild/connect-web/dist/esm/connect-transport.js:57
                        throw new ConnectError(`HTTP ${response.status} ${response.statusText}`, codeFromConnectHttpStatus(response.status));
                              ^

ConnectError: [internal] HTTP 415 Unsupported Media Type
    at file:///Users/mfridman/debug-generation/connect-web/old-remote/node_modules/@bufbuild/connect-web/dist/esm/connect-transport.js:57:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.unary (file:///Users/mfridman/debug-generation/connect-web/old-remote/node_modules/@bufbuild/connect-web/dist/esm/connect-transport.js:28:24)
    at async Object.say (file:///Users/mfridman/debug-generation/connect-web/old-remote/node_modules/@bufbuild/connect-web/dist/esm/promise-client.js:35:26)
    at async file:///Users/mfridman/debug-generation/connect-web/old-remote/hello.js:26:22 {
  rawMessage: 'HTTP 415 Unsupported Media Type',
  code: 13,
```

Diving into the code a bit more, it turns out there might be compatibility issues with how Node fetch handles the Header vs something like `node-fetch`.

Two things resolved the issue for me:

1. converting Header to a plain serializable javascript object (modifying the generated code)

```
const requestHeaders = Object.fromEntries(unaryRequest.header.entries())
const response = await fetch(
  unaryRequest.url,
  Object.assign(Object.assign({}, unaryRequest.init), { headers: requestHeaders ...
```

2. importing `node-fetch` in `connect-transport.js` (modifying the generated code)

So, is there a bug in how Node's fetch implementation is handling the Headers we pass it, are we doing something wrong, or is it something in my setup?

**Comment by sonnysideup** [comment]
What was the actual problem and/or solution here?

**Comment by timostamm** [comment]
Node v18 stopped hiding it's fetch() implementation behind the `--experimental-global-fetch` flag. But the fetch() implementation was still a bit buggy. I don't remember what the problem was exactly, looks like fetch() wasn't accepting a Headers object, only a plain object literal.

The solution is to update to a more recent release of Node.js that doesn't have this bug. Fetch is "experimental" until v21, although I'm not aware of any issues with the current LTS v20.
