### ISSUE TITLE
Detect closed socket in server stream? 

### ISSUE THREAD

**Issue by par5er** [connectrpc/connect-es#276]
I am sending a stream of messages from the server to the client. I would like to measure how long the connection was open (ie., know when the socket closes). I am currently doing it like this:

```go
// Ping client every 2 seconds to ensure socket still open
t := time.NewTicker(time.Second * 2)

for {
    <-t.C
    if err := stream.Send(PING_MSG); err != nil {
        // Client has disconnected
    }
}
```

The problem with this, though, is that `err` is non-nil only on the 3rd `.Send()`. I expect it to error immediately after the socket is closed. Am I missing something?

Edit: Seems it errors after the _4th_ `.Send()`, not the 3rd [if it makes any difference :)]

**Comment by akshayjshah** [comment]
Hi @par5er! You've filed this issue in `bufbuild/connect-web`, which is an RPC implementation for web browsers. Your code is Go, though - should I move this to `bufbuild/connect-go`?

**Comment by akshayjshah** [comment]
No problem, I'll move it later on this weekend :)

In the meantime, can you share a complete reproduction of the issue?
