### ISSUE TITLE
Provide express' req/res.locals inside HandlerContext

### ISSUE THREAD

**Issue by kruegernet** [connectrpc/connect-es#586]
**Is your feature request related to a problem? Please describe.**
When migrating an existing express/REST service to use connect/gRPC, it will be a typical scenario that an RPC handler must work with the existing express middleware. If we cannot access req.locals or res.locals, for some users adopting connect-es will be impossible.

**Describe the solution you'd like**
Please provide access to req/res.locals via the HandlerContext. 

This request is for Connect for Node.js.

**Describe alternatives you've considered**
I would personally prefer, at least during beta, that the entire raw express req and res are exposed to us via HandlerContext. It's not clear to me how you all plan to address authentication/authorization or middleware generally, or how you intend to relate http middleware to gRPC interceptors. Until these are resolved it remains unclear how folks can migrate existing services or do serious work with connect-es.

**Comment by mfecteau42** [comment]
A workaround was found by modifying this file : **@bufbuild/connect/dist/esm/protocol-connect/handler-factory.js**

By adding this code at the right place, in both functions **createUnaryHandler** and **createStreamHandler**, the res.locals variable becomes available : 
```js
if (req.locals) {
    context.locals = req.locals
}
```

**Comment by srikrsna-buf** [comment]
#835
