### ISSUE TITLE
ERR_INVALID_HTTP_RESPONSE when trying to connect to grpc server

### ISSUE THREAD

**Issue by thatsnoi** [connectrpc/connect-es#785]
TLDR: Trying to connect to a python grpc server from a React app throws ERR_INVALID_HTTP_RESPONSE

The bug is described [here](https://stackoverflow.com/questions/76871048/err-invalid-http-response-using-bufbuild-connect-to-connect-to-a-python-grpcio). This is not by me but pretty much the same bug I'm encountering. I also tried using createGrpcWebTransport.

**Environment (please complete the following information):**
- @connectrpc/connect-web version: 0.13.1
- Frontend framework and version: next@13.4.19
- Node.js version: 16.6
- Browser and version: Chrome 115.0.5790.170

**Comment by MunzerDw** [comment]
Also facing the same issue, would appreciate any help.

**Comment by srikrsna-buf** [comment]
Hey! grpc and grpc-web are two different protocols, the latter was created to make grpc work in browsers (unary and server streaming). To my knowledge python grpc doesn't support grpc-web it only supports regular grpc which requires HTTP/2 with trailer support (unavailable in browsers). Connect is a similar simpler protocol that works in web browsers.

You have two options:
- Use a proxy that does the translation from connect/grpc-web to grpc. Envoy is the usual choice but there are [others](https://github.com/grpc/grpc-web#proxy-interoperability).
- Switch to a grpc implementation that supports grpc-web/connect, a quick google search revealed https://github.com/public/sonora that claims grpc-web support in python.

Closing this issue for now, feel free to reopen if needed.
