### ISSUE TITLE
Difficulty Accessing Authenticated User Object from Passport Middleware

### ISSUE THREAD

**Issue by akosyakov** [connectrpc/connect-es#818]
I'm using Passport's authentication middleware, which provides an authenticated user object on a request ([Passport Middleware Documentation](https://www.passportjs.org/concepts/authentication/middleware/)). I'm struggling to access this user object in services.

A potential workaround is to do a double lookup in the service based on the cookie, but I'd prefer not to. It seems counterintuitive for a library to obscure objects, especially when there's an ecosystem contributing to them. This makes integration challenging.

**Comment by akosyakov** [comment]
Figured out that I can use ts augmentation to add more properties and mutate context via proxies.

**Comment by srikrsna-buf** [comment]
#835
