### ISSUE TITLE
ConnectError: [unknown] network error

### ISSUE THREAD

**Issue by akosyakov** [connectrpc/connect-es#836]
**Describe the bug**

We are seeing in our auto error reporting from the browser application:

```
ConnectError: [unknown] network error
    at Function.value (/workspace/gitpod/node_modules/@bufbuild/connect/dist/esm/connect-error.js:72:19)
    at from (/workspace/gitpod/node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:103:35)
```

It seems some network issues are not recognized like Unavailable.

**To Reproduce**

Not sure. Something related to network issues. GCP load balancer resets connections each 10 mins, maybe related.
It was also coming from server side streaming API, i.e. long running connection.

**Environment (please complete the following information):**

We are using 0.13.0 for all deps right now.

**Additional context**

**Comment by akosyakov** [comment]
Yeah it happens when server-stream after 10mins when GCP resets the connection:
<img width="887" alt="Screenshot 2023-09-20 at 17 12 30" src="https://github.com/connectrpc/connect-es/assets/3082655/d11a8f63-e99c-4494-9b47-ffdf976995a3">

**Comment by akosyakov** [comment]
It happens here:
<img width="1015" alt="Screenshot 2023-09-20 at 20 51 45" src="https://github.com/connectrpc/connect-es/assets/3082655/c4cecb9d-5318-4701-b2b6-d951bfd589c0">

**Comment by akosyakov** [comment]
Is there a way to set timeout on stream that they get closed a bit earlier with more expected error? Asking because I see different browser behaves differently in this case: https://github.com/kyma-project/busola/blob/ebad26a4f8fd86905dcaa43ada088f7cd15c8f80/src/shared/hooks/BackendAPI/useGet.js#L161-L165

**Comment by srikrsna-buf** [comment]
Hey! Your analysis seems accurate. Unfortunately, `fetch` doesn't provide distinguishable errors across browser implementations. Hence we can't reliably address this within `connect-web`.

The solution you arrived at seems reasonable, timeouts can be be set on a per rpc basis and retried. Once #799 is addressed they can be set at a transport level.

Closing this for now, feel free to reopen if needed.

**Comment by akosyakov** [comment]
@srikrsna-buf I'm considering to add instead server side timeout that all API clients have the same experience. Do you think it is sensible? feasible? common?

**Comment by srikrsna-buf** [comment]
Server side timeouts sound good to me as a way to set resource limits. If there are non web clients, no need to enforce the limit for them which would otherwise be acceptable.
