### ISSUE TITLE
Investigate removing subpath fallback files

### ISSUE THREAD

**Issue by smaye81** [connectrpc/connect-es#839]
Currently, we have fallback files in `packages/connect` for consumers that don't support subpath exports (`protocol.js`, `protocol-connect.js`, `protocol-grpc.js`, and `protocol-grpc-web.js`). 

However, these files may not be needed as it is basically supporting Node.js v10 module resolution. Since Node 10 has been EOL for more than two years, we could potentially remove these altogether.

This could potentially break some bundlers, so we'd have to conduct an investigation into whether we could safely remove them.

For further context, see https://github.com/connectrpc/connect-es/pull/838#issuecomment-1737869511

**Comment by timostamm** [comment]
We have removed the fallback files in https://github.com/bufbuild/protobuf-es/pull/804.
If this does not cause any issues, we can safely do it here as well.

**Comment by timostamm** [comment]
With Parcel and Metro, subpath exports need to be enabled, see https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#parcelmetro-fails-to-resolve-imports

**Comment by timostamm** [comment]
V2 removes subpath fallbacks for Node10.
