### ISSUE TITLE
Deprecate `@bufbuild/*` packages

### ISSUE THREAD

**Issue by fubhy** [connectrpc/connect-es#845]
**Is your feature request related to a problem? Please describe.**
The `@bufbuild/connect-*` packages still exist on the npm registry and there's no indication of or reference to the new `@connectrpc/*` packages there. This means that people who usually regularly run `pnpm update -irL` will not see that updates are indeed happening, just under a different package name ;-)

**Describe the solution you'd like**
Tag the `@bufbuild/connect-*` packages as deprecated with a hint pointing at their successor(s).

**Comment by timostamm** [comment]
Good call 🙂

Within the last week, a good chunk of users moved from @bufbuild/connect@0.13.0 to @connectrpc/connect. We want to ride that momentum for a bit, but definitely deprecated the old names soon.

**Comment by timostamm** [comment]
All Connect packages in the `@bufbuild` scope have just been deprecated. 

To switch to the new scope `@connectrpc`, you can run `npx @connectrpc/connect-migrate@latest`. For details, see https://github.com/connectrpc/connect-es/releases/tag/v0.13.1
