### ISSUE TITLE
Pinging idle connection before sending request is ignored and node process exits unexpectedly

### ISSUE THREAD

**Issue by jeanp413** [connectrpc/connect-es#860]
**Describe the bug**

After being idle from a long time and calling a method, the second call is skipped completely and the node process exits unexpectedly.
This is because the ping call in the verify state is done with the socket unrefed.

**To Reproduce**
Tested this on linux using latest version:

```js
    const transport = createConnectTransport({
        baseUrl: serviceUrl.toString(),
        httpVersion: '2',
        interceptors: [authInterceptor],
        useBinaryFormat: true,
       pingIntervalMs: 120000,
    });

    const service = createPromiseClient(MyService, transport);

        const response1 = await service.method({});
        console.log(`===> ${new Date()} On method response}`, response1);

        console.log(`===> ${new Date()} Going to sleep`);
        await timeout(10*60*1000);
        console.log(`===> ${new Date()} Awake`);

        // This await is ignored and the node process exits unexpectedly
        const response2 = await service.method({});
        console.log(`===> ${new Date()} On method response2}`, response2);
```

**Additional context**

**Comment by srikrsna-buf** [comment]
Hey! Can you give the node version that you are using, I am unable to reproduce using node `20.7.0` with:
```ts
const transport = createConnectTransport({
  baseUrl: "https://demo.connectrpc.com",
  httpVersion: "2",
  useBinaryFormat: true,
  pingIntervalMs: 120000,
});
const service = createPromiseClient(ElizaService, transport);
const response1 = await service.say({ sentence: "Hello" });
console.log(`===> ${new Date()} On method response}`, response1);
console.log(`===> ${new Date()} Going to sleep`);
await new Promise((resolve) => setTimeout(resolve, 10 * 60 * 1000));
console.log(`===> ${new Date()} Awake`);
// This await is ignored and the node process exits unexpectedly
const response2 = await service.say({});
console.log(`===> ${new Date()} On method response2}`, response2);
```

We don't send ping frames for idle connections, unless `pingIdleConnection` is set to true along with `pingIntervalMs`. So it should not be a ping issue in this case. Regarding the `unref`, it should not be a problem here, as the execution of the call itself will result in events. Besides, we call `ref` before we send any ping frames when we have an active stream: https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L619

Can you also try with the sample I pasted and let us know the results, it is similar I just removed the auth interceptor and used the demo server.

**Comment by jeanp413** [comment]
@srikrsna-buf I'm using node 18

> We don't send ping frames for idle connections, unless pingIdleConnection is set to true along with pingIntervalMs. So it should not be a ping issue in this case. Regarding the unref, it should not be a problem here, as the execution of the call itself will result in events. Besides, we call ref before we send any ping frames when we have an active stream:

When `pingIntervalMs` is specified a ping frame is send before doing the actual request to [verify the connection](https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L273), it goes to [verifying state](https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L483-L506) and the connection is unrefed in that case.

> Can you also try with the sample I pasted and let us know the results, it is similar I just removed the auth interceptor and used the demo server.

Will try your sample

**Comment by srikrsna-buf** [comment]
> When `pingIntervalMs` is specified a ping frame is send before doing the actual request to [verify the connection](https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L273), it goes to [verifying state](https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L483-L506) and the connection is unrefed in that case.

Yes, but we wait for the [verified promise to complete](https://github.com/connectrpc/connect-es/blob/85e0432e04584a8e287d3192d985d5db17df7665/packages/connect-node/src/http2-session-manager.ts#L294) that should hold the event loop, but I see what your saying I'll try to trigger the verify in my test.

**Comment by jeanp413** [comment]
@srikrsna-buf I can repro with your sample, are you using Linux?

**Comment by srikrsna-buf** [comment]
Me too I just got it to trigger the verify flow. I'll send a fix soon Thank you!

**Comment by timostamm** [comment]
Thanks for the detailed report, @jeanp413 ❤️

**Comment by jeanp413** [comment]
@srikrsna-buf @timostamm looks like this wasn't the only bug, now the event loop doesn't exit but when going from ready state to verifying the `this.s.onExitState?.()` is invoked clearing the `pingTimeoutId` so the ping won't timeout after `pingTimeoutMs`, it will timeout eventually after aorund 17 minutes with `Error [ERR_HTTP2_PING_CANCEL]: HTTP2 ping cancelled`

**Comment by srikrsna-buf** [comment]
@jeanp413  Brilliant! You may have found the cause for #683 as well, I can reproduce the behavior with a test, sending a fix. Thank you!
