### ISSUE TITLE
Enum from proto is compiled to Typescript Enum, this however create a binary serialisation error when Enum is created from string.

### ISSUE THREAD

**Issue by liufuyang** [connectrpc/connect-es#883]
**Describe the bug**

For example I have some proto with some enums and in the compiled TS is looks like this:
```ts
export enum State {
 STATE_UNSPECIFIED = 0,
 A = 1,
 B = 2,
}
```

Then I used some selection UI components, and if `"A"` for example is selected, it creates a `State` with code such as `const state = State[a as keyof typeof State]` behind the scene. 

The using this `state`, which in TS has the type of `State`, and then set it to a proto message on a State field. Then do a simple grpc call, I got this error:

```
ConnectError: [internal] serialize binary: invalid int 32: string
    at serialize (serialization.js:104:23)
    at next (grpc-web-transport.js:77:169)
    at client.ts:109:12
    at async Object.unary (grpc-web-transport.js:55:20)
    at async Object.updateVehicle (promise-client.js:66:26)
```

**To Reproduce**

With a proto enum and TS generated code such as:
```ts
export enum State {
 STATE_UNSPECIFIED = 0,
 A = 1,
 B = 2,
}
```

Then create some simple grpc call with a message having an enum field, with the state enum created as 
```ts
const a = "1"
const state = State[a as keyof typeof State]

const message = {state}
// then use the massage for some grpc remote call
// this error should show up?
```

Switching above code to:
```ts
const state = State.A
```
will stop the error.

But from the user side, in TS, it is difficult to now whether an enum is presented by a number or a string, as they are both valid. So perhaps when we do grpc proto serialization, we should always try to use the enum's number representation?

**Environment (please complete the following information):**
- @connectrpc/connect-web version: `1.1.2`
- @connectrpc/connect-node version: `1.1.2`
- Frontend framework and version: (for example, `react@18.2.0`)
- Node.js version: (for example, `18.0.0`)

**Additional context**

**Comment by liufuyang** [comment]
I tried to make some sample code here https://github.com/liufuyang/examples-es/tree/show-enum-issue/express 

The diff can be seen [here](https://github.com/connectrpc/examples-es/compare/main...liufuyang:examples-es:show-enum-issue?expand=1).

So after running a server, then run the client code, will see these output:

```
(show-enum-issue *%) 🦀 👉  cd express/
fuyangl@Fuyangs-MacBook-Pro:~/einride/examples-es/express 
(show-enum-issue *%) 🦀 👉  npm run client

> buf-express@0.1.0 client
> tsx client.ts

What is your name?
> whatever
A
string
2
number
Hi whatever, I'm Eliza
Before we begin, whatever in let me tell you something about myself.
I'm a Rogerian psychotherapist.
How are you feeling today?
> good
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ConnectError: [internal] serialize binary: invalid int 32: string
    at Object.serialize (/Users/fuyangl/einride/examples-es/express/node_modules/@connectrpc/connect/dist/cjs/protocol/serialization.js:111:23)
    at Object.serialize (/Users/fuyangl/einride/examples-es/express/node_modules/@connectrpc/connect/dist/cjs/protocol/serialization.js:79:41)
    at <anonymous> (/Users/fuyangl/einride/examples-es/express/node_modules/@connectrpc/connect/dist/cjs/protocol/async-iterable.js:348:52)
    at Generator.next (<anonymous>)
    at resume (/Users/fuyangl/einride/examples-es/express/node_modules/@connectrpc/connect/dist/cjs/protocol/async-iterable.js:28:43)
    at fulfill (/Users/fuyangl/einride/examples-es/express/node_modules/@connectrpc/connect/dist/cjs/protocol/async-iterable.js:30:31) {
  rawMessage: 'serialize binary: invalid int 32: string',
  code: 13,
  metadata: Headers {
    [Symbol(headers list)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: Map(0) {},
      [Symbol(headers map sorted)]: null
    },
    [Symbol(guard)]: 'none'
  },
  details: [],
  cause: undefined
}

Node.js v18.16.1
```

**Comment by timostamm** [comment]
Hey @liufuyang, the issue here is that you pass a `string` for a property that must be a number (an integer enum value:

```ts
const stateA = State[a as keyof typeof State]
```

The TypeScript compiler believes `stateA` to be a `State` (one of the valid enum values) because of your cast, but it's actually a string. If you remove the cast, you will see the compiler error:

```ts
const a = "1"
const stateA = State[a];

// ...

const res = await client.say({ sentence, state: stateA}); 
//                                       ^^^^^
// TS2322: Type string is not assignable to type State | undefined
```

**Comment by timostamm** [comment]
You want to present the enum values as select options in a UI, right?

This can be surprisingly complicated with a regular TypeScript enum (because the enum is a [lookup object](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-runtime)), but protobuf-es provides a convenient helper:

```ts
import {proto3} from "@bufbuild/protobuf";

const options = proto3.getEnumType(State).values;
for (const opt of options) {
  opt.no // The numeric enumeration value, as specified in the protobuf source.
  opt.name // The name of the enumeration value, as specified in the protobuf source.
  opt.localName // The name of the enumeration value in generated code.
}

const opt = proto3.getEnumType(State).findName("A");
const selected: State = opt?.no ?? State.UNKNOWN;
```

It depends on your UI framework how you wire up the options, but `getEnumType` gives you convenient programmatic access to all enum values.

**Comment by liufuyang** [comment]
Aha, your helper code is very helpful. Indeed I was using some UI framework and when wire an enum onto a selection component, I always get a string type back on the select event, no matter it is an "A" or a "0" if I use the enum directly as value on it.

I think I can use your helper code to get around it. Otherwise, I can also talk to the UI framework and perhaps can make the type of the event more flexible.

Thank you very much. I will just close this issue now :)
