### ISSUE TITLE
Error handling with express connect middleware

### ISSUE THREAD

**Issue by sayyajp** [connectrpc/connect-es#885]
#### Question
I want to handle error produced in ExpressConnectMiddleware.
But in [ExpressConnectMiddleware](https://github.com/connectrpc/connect-es/blob/dbde9a0f33ea903577c494559e63942a9e8146c1/packages/connect-express/src/express-connect-middleware.ts#L93-L104), it doesn't seem to pass err like `next(err)`.
So I can't handle error in express.
Is there any solution?

Thanks

**Comment by timostamm** [comment]
Hey @sayyajp, we looked into this before in #551. Our middleware _does_ end the request-response cycle. If an error occurs in an RPC, we write back an error response in the correct protocol-specific format. I am not sure how we could change behavior without causing issues. 

How do you want to handle the error in express? Maybe there is an alternative to support your use case.

**Comment by sayyajp** [comment]
@timostamm Thanks for reply.
I might be able to resolve the problem when I follow [comment](https://github.com/connectrpc/connect-es/issues/551#issuecomment-1494532773).
If I should have problem yet, let me comment again.
