### ISSUE TITLE
How can I use middleware in the server library?

### ISSUE THREAD

**Issue by graforlock** [connectrpc/connect-es#960]
I am struggling to see how can I use backend middleware using the connect server. For example, to automatically parse things like session cookies. At the moment I am doing it in every handler like this:

```typescript
export default (router: ConnectRouter) =>
  router.service(MarketplaceService, {
    async getTask(opts: { taskId: string }, ctx) {
      const session = sessionService.getSession(ctx.requestHeader.get('cookie'));

      return await tasksUseCases.getTaskById(session.id, opts.taskId);
    },
}
```

But surely there must be a better way?

(I cannot use connect-web because those cookies are httpOnly)

**Comment by srikrsna-buf** [comment]
Hey! We don't yet have server side interceptors it is tracked in #527. But for the use case that you highlighted you can parse the cookie at the server(fastify/express) layer and add the parsed information to the context. This was added in `v1.1.0`. There's a similar example in the [release notes](https://github.com/connectrpc/connect-es/releases/tag/v1.1.0)
