### ISSUE TITLE
Otel support just like otelconnect-go does

### ISSUE THREAD

**Issue by danvergara** [connectrpc/connect-es#988]
**Is your feature request related to a problem? Please describe.**

Is there a way to add support for Open Telemetry instrumentation just like [connect-go](https://buf.build/blog/connect-opentelemetry-go) has? 
The current stack of the company I work for has some apps using connect and we're in the middle of the endeavor of instrumenting the most critical  apps and workflows we maintain.

**Describe the solution you'd like**
There's a function called `createConnectTransport` that has a field called `interceptors` that can be used to intercept requests to add headers such as `traceparent`.

The request is for Connect for Node.js

**Describe alternatives you've considered**
Another alternative is doing that by ourselves, but we might need an example.

**Comment by srikrsna-buf** [comment]
> Another alternative is doing that by ourselves, but we might need an example.


With #982 merged, in the next release you can use an interceptor to add this functionality. I'll post an example here once the docs are updated

**Comment by danvergara** [comment]
@srikrsna-buf Nice!
Looking forward to it!

Thanks!

**Comment by srikrsna-buf** [comment]
We just published a preview release with support for server side interceptors: `npm i @connectrpc/connect@next`.

The docs for interceptors are [here](https://connect-git-sk-esinterceptors-connectrpc.vercel.app/docs/node/interceptors).

**Comment by danvergara** [comment]
Looking forward for the actual release!

In the meantime, I'll read the docs and telling my teammates that the solution to our current issue is on its way.

Thanks for the support @srikrsna-buf!!!

**Comment by chrispine** [comment]
Closing this issue, but feel free to re-open (or create a new issue) if needed. Thanks!

**Comment by danvergara** [comment]
Well, I'd like to keep it open until v1.4.0 comes out. At least, I'd like to know how long until the next release. My CTO is asking me.

**Comment by danvergara** [comment]
Thanks @chrispine
Really appreciated.

**Comment by chrispine** [comment]
Here you go, @danvergara: https://github.com/connectrpc/connect-es/releases/tag/v1.4.0

I'll close this now, but as always, reach back out or re-open if needed. Thanks!

**Comment by danvergara** [comment]
Thanks so much!!!!!!!!!
