### ISSUE TITLE
Request-scoped logging

### ISSUE THREAD

**Issue by macourteau** [connectrpc/connect-es#990]
Fastify [includes a `log` member in the request](https://fastify.dev/docs/v2.15.x/Documentation/Logging/), which makes it possible to output request-scoped logs. Specifically, the output logs include a `reqId` which is unique to every request, but consistent across all logs generated within the scope of a request, making it possible to better analyze logs later.

It would be very useful to be able to access this logger from within request handlers. I presume the logger could output non-request-scoped logs in other plugins if the system they integrate into doesn't have request-scoped logging (e.g. connect-express, AFAICT).

This would be useful in Connect for Node.js - I don't think it would apply to Connect for Web.

I have tried to capture the `log` member from the `Fastify` object and use it within request handlers, but the logs generated by that logger are not request-scoped.

**Comment by smaye81** [comment]
Hi @macourteau you can do this now using context. Take a look at #835 for an example of how to do it. Specifically this [comment](https://github.com/connectrpc/connect-es/pull/835#issuecomment-1760714671). 

Let me know if that helps.

**Comment by macourteau** [comment]
Ah, yes, that absolutely works - thanks! I think it would be useful to add this to the documentation, perhaps in the [Context](https://connectrpc.com/docs/node/implementing-services#context) section, or an "Advanced" section.

**Comment by smaye81** [comment]
Totally agree @macourteau . We are actually updating the docs to include this, they're just still in-flight. You can see the PR [here](https://github.com/connectrpc/connectrpc.com/pull/128).
